name: Deploy to Cloudflare

on:
  push:
    branches:
      - cloudflare-debug  # Trigger deploy only on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List files to check directory structure
      run: ls -la

    # Set working directory to the folder where Cloudflare files are located
    - name: Set working directory for Cloudflare deployment
      run: cd CheckMateCloudFlare  # Update this to the correct folder path if needed

    # Install dependencies (ensure package.json exists in CheckMateCloudFlare folder)
    - name: Install dependencies
      run: npm install  # Make sure package.json is in this folder

    # Build the project
    - name: Build project
      run: npm run build  # This command may need to be adjusted based on your build process

    # Deploy to Cloudflare
    - name: Deploy to Cloudflare
      run: wrangler publish  # Make sure you have wrangler set up correctly in the folder
