name: Deploy to Cloudflare

on:
  push:
    branches:
<<<<<<< HEAD
<<<<<<< HEAD
      - cloudflare-debug  # Trigger deploy only on push to the main branch
=======
      - main  # Trigger deploy only on push to the main branch
>>>>>>> fe10ca410c6649c6ae5285833f21693d817e33a4
=======
      - cloudflare-debug  # Trigger deploy only on push to the main branch
>>>>>>> features/task-display-and-function

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> features/task-display-and-function
    - name: List files to check directory structure
      run: ls -la

    # Set working directory to the folder where Cloudflare files are located
    - name: Set working directory for Cloudflare deployment
      run: cd CheckMateCloudFlare  # Update this to the correct folder path if needed

    # Install dependencies (ensure package.json exists in CheckMateCloudFlare folder)
    - name: Install dependencies
      run: npm install  # Make sure package.json is in this folder

    # Build the project
    - name: Build project
      run: npm run build  # This command may need to be adjusted based on your build process

    # Deploy to Cloudflare
    - name: Deploy to Cloudflare
<<<<<<< HEAD
      run: wrangler publish  # Make sure you have wrangler set up correctly in the folder
=======
    # Set working directory to the folder where Cloudflare files are located
    - name: Set working directory for Cloudflare deployment
      run: cd cloudflare/CheckMateCloudFlare  # Update this to the correct folder path if needed

    # Install dependencies (ensure package.json exists in CheckMateCloudFlare folder)
    - name: Install dependencies
      run: |
        cd cloudflare/CheckMateCloudFlare
        npm install  # Make sure package.json is in this folder

    # Build the project
    - name: Build project
      run: |
        cd cloudflare/CheckMateCloudFlare
        npm run build  # This command may need to be adjusted based on your build process

    # Deploy to Cloudflare
    - name: Deploy to Cloudflare
      run: |
        cd cloudflare/CheckMateCloudFlare
        npx wrangler publish  # Make sure you have wrangler set up correctly in the folder
>>>>>>> fe10ca410c6649c6ae5285833f21693d817e33a4
=======
      run: wrangler deploy  # Make sure you have wrangler set up correctly in the folder
>>>>>>> features/task-display-and-function
